# Usar la última versión 2.1 del motor de proceso de flujo CircleCI.
# Ver: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Usar un paquete de configuración llamado orb.
orbs:
  # Declarar una dependencia en la welcome-orb
  bienvenida: circleci/node@1.1
# Orquestar o programar un grupo de trabajos
jobs:
  construir:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test
